use std::{collections::HashMap, fs};

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::schema::{Property, Structure, Type};

// TODO: Add CI to ensure the locally copied metaModel matches the one at this URL.
// const METAMODEL_URL: &str = "https://raw.githubusercontent.com/microsoft/language-server-protocol/gh-pages/_specifications/lsp/3.18/metaModel/metaModel.json";

mod schema {
    // TODO: Add CI check to ensure that the locally copied schema still matches the GitHub source.
    typify::import_types!("metaModel.schema.json");
}

/// Converts from camelCase (or PascalCase) to snake_case.
fn camel_to_snake(camel: &str) -> String {
    let mut snake = String::with_capacity(camel.len() + 4);

    for (i, char) in camel.chars().enumerate() {
        if char.is_ascii_uppercase() {
            if i > 0 {
                snake.push('_');
            }
            snake.push(char.to_ascii_lowercase());
        } else {
            snake.push(char);
        }
    }

    snake
}

fn resolve_struct_properties(
    properties: Vec<Property>,
    extends: Vec<Type>,
    mixins: Vec<Type>,
    structs_map: &HashMap<String, Structure>,
) -> (Vec<Property>, Vec<TokenStream>) {
    let mut structure_props = properties;
    let mut mixin_props = Vec::with_capacity(extends.len() + mixins.len());
    mixins.into_iter().chain(extends).for_each(|type_| {
        let Type::ReferenceType(reference_type) = type_ else {
            panic!("Expected mixin/extend type to be a reference: {:?}", type_);
        };
        // Inline mixin/extend structs which start with an underscore. This is for convenience.
        if reference_type.name.starts_with('_') {
            let type_ = structs_map.get(&reference_type.name);
            match type_ {
                Some(structure) => {
                    let (inner_sp, inner_mp) = resolve_struct_properties(
                        structure.properties.clone(),
                        structure.extends.clone(),
                        structure.mixins.clone(),
                        structs_map,
                    );
                    structure_props.extend(inner_sp);
                    mixin_props.extend(inner_mp);
                }
                _ => panic!("Could not inline type {}", reference_type.name),
            }
            return;
        }
        let prop_name = format_ident!("{}", camel_to_snake(&reference_type.name));
        // TODO
        let type_ = quote! { i32 };
        mixin_props.push(quote! {
            #[serde(flatten)]
            pub #prop_name: #type_,
        });
    });
    (structure_props, mixin_props)
}

fn main() {
    // Run the generator.
    let model_string =
        fs::read_to_string("xtask/metaModel.json").expect("No local metaModel copy found");

    let model: schema::MetaModel = serde_json::from_str(&model_string).unwrap();

    println!(
        "Generating types for LSP version {}...",
        model.meta_data.version
    );

    let structs_map: HashMap<String, Structure> = model
        .structures
        .clone()
        .into_iter()
        .map(|s| (s.name.clone(), s))
        .collect();

    let preamble = quote! {
        //! This file is generated by an xtask. Do not edit.
    };

    let imports = quote! {
        use serde::{Deserialize, Serialize};
    };

    let structures: Vec<TokenStream> = model
        .structures
        .into_iter()
        .map(|structure| {
            // We inline these structs; consider them private and do not generate.
            if structure.name.starts_with('_') {
                return quote! {};
            }

            // TODO: Add `Default` and/or `Copy` if all properties implement them.
            let mut attributes = quote! {
                #[derive(Serialize, Deserialize, PartialEq, Debug, Eq, Clone)]
                #[serde(rename_all = "camelCase")]
            };
            let name = format_ident!("{}", structure.name);
            if let Some(note) = structure.deprecated {
                attributes = quote! {
                    #attributes
                    #[deprecated(note = #note)]
                };
            }
            let documentation = structure
                .documentation
                .map(|doc| {
                    let lines = doc.split('\n');
                    lines
                        .map(|line| {
                            let line = if line.is_empty() {
                                line.to_string()
                            } else {
                                [" ", line].concat()
                            };
                            quote! { #[doc = #line] }
                        })
                        .collect::<Vec<_>>()
                })
                .unwrap_or_default();
            let has_kind = structure
                .properties
                .iter()
                .find(|property| property.name == "kind")
                .is_some();
            let (structure_props, mixin_props) = resolve_struct_properties(
                structure.properties,
                structure.extends,
                structure.mixins,
                &structs_map,
            );
            let properties = structure_props
                .into_iter()
                .map(|property| {
                    let deprecated = property.deprecated.map(|note| {
                        quote! {
                            #[deprecated(note = #note)]
                        }
                    });
                    let documentation = property
                        .documentation
                        .map(|doc| {
                            let lines = doc.split('\n');
                            lines
                                .map(|line| {
                                    let line = if line.is_empty() {
                                        line.to_string()
                                    } else {
                                        [" ", line].concat()
                                    };
                                    quote! { #[doc = #line] }
                                })
                                .collect::<Vec<_>>()
                        })
                        .unwrap_or_default();

                    let (name, mut serde_attributes) = if property.name == "type" {
                        assert!(
                            !has_kind,
                            "Structure {} already has `kind` property",
                            structure.name
                        );
                        (format_ident!("kind"), quote! { #[serde(rename = "type")] })
                    } else {
                        (
                            format_ident!("{}", camel_to_snake(&property.name)),
                            quote! {},
                        )
                    };
                    // TODO
                    let mut type_ = quote! { i32 };

                    if property.optional == Some(true) {
                        serde_attributes = quote! {
                            #serde_attributes
                            #[serde(skip_serializing_if = "Option::is_none")]
                        };
                        type_ = quote! {
                            Option<#type_>
                        }
                    }

                    quote! {
                        #(#documentation)*
                        #deprecated
                        #serde_attributes
                        pub #name: #type_,
                    }
                })
                .chain(mixin_props);

            quote! {
                #(#documentation)*
                #attributes
                pub struct #name {
                    #(#properties)*
                }
            }
        })
        .collect();

    let all_items = [&[preamble], &[imports], &structures[..]].concat();

    let formatted_items: Vec<_> = all_items
        .into_iter()
        .map(|request| {
            let syntax_tree = syn::parse2(request).unwrap();

            prettyplease::unparse(&syntax_tree)
        })
        .collect();

    fs::write("src/generated.rs", formatted_items.join("\n")).unwrap();

    println!("Generation complete! 🌟");
}
