//! This file is generated by an xtask. Do not edit.

pub struct ImplementationParams {}

pub struct Location {}

pub struct ImplementationRegistrationOptions {}

pub struct TypeDefinitionParams {}

pub struct TypeDefinitionRegistrationOptions {}

pub struct WorkspaceFolder {}

pub struct DidChangeWorkspaceFoldersParams {}

pub struct ConfigurationParams {}

pub struct DocumentColorParams {}

pub struct ColorInformation {}

pub struct DocumentColorRegistrationOptions {}

pub struct ColorPresentationParams {}

pub struct ColorPresentation {}

pub struct WorkDoneProgressOptions {}

pub struct TextDocumentRegistrationOptions {}

pub struct FoldingRangeParams {}

pub struct FoldingRange {}

pub struct FoldingRangeRegistrationOptions {}

pub struct DeclarationParams {}

pub struct DeclarationRegistrationOptions {}

pub struct SelectionRangeParams {}

pub struct SelectionRange {}

pub struct SelectionRangeRegistrationOptions {}

pub struct WorkDoneProgressCreateParams {}

pub struct WorkDoneProgressCancelParams {}

pub struct CallHierarchyPrepareParams {}

pub struct CallHierarchyItem {}

pub struct CallHierarchyRegistrationOptions {}

pub struct CallHierarchyIncomingCallsParams {}

pub struct CallHierarchyIncomingCall {}

pub struct CallHierarchyOutgoingCallsParams {}

pub struct CallHierarchyOutgoingCall {}

pub struct SemanticTokensParams {}

pub struct SemanticTokens {}

pub struct SemanticTokensPartialResult {}

pub struct SemanticTokensRegistrationOptions {}

pub struct SemanticTokensDeltaParams {}

pub struct SemanticTokensDelta {}

pub struct SemanticTokensDeltaPartialResult {}

pub struct SemanticTokensRangeParams {}

pub struct ShowDocumentParams {}

pub struct ShowDocumentResult {}

pub struct LinkedEditingRangeParams {}

pub struct LinkedEditingRanges {}

pub struct LinkedEditingRangeRegistrationOptions {}

pub struct CreateFilesParams {}

pub struct WorkspaceEdit {}

pub struct FileOperationRegistrationOptions {}

pub struct RenameFilesParams {}

pub struct DeleteFilesParams {}

pub struct MonikerParams {}

pub struct Moniker {}

pub struct MonikerRegistrationOptions {}

pub struct TypeHierarchyPrepareParams {}

pub struct TypeHierarchyItem {}

pub struct TypeHierarchyRegistrationOptions {}

pub struct TypeHierarchySupertypesParams {}

pub struct TypeHierarchySubtypesParams {}

pub struct InlineValueParams {}

pub struct InlineValueRegistrationOptions {}

pub struct InlayHintParams {}

pub struct InlayHint {}

pub struct InlayHintRegistrationOptions {}

pub struct DocumentDiagnosticParams {}

pub struct DocumentDiagnosticReportPartialResult {}

pub struct DiagnosticServerCancellationData {}

pub struct DiagnosticRegistrationOptions {}

pub struct WorkspaceDiagnosticParams {}

pub struct WorkspaceDiagnosticReport {}

pub struct WorkspaceDiagnosticReportPartialResult {}

pub struct DidOpenNotebookDocumentParams {}

pub struct NotebookDocumentSyncRegistrationOptions {}

pub struct DidChangeNotebookDocumentParams {}

pub struct DidSaveNotebookDocumentParams {}

pub struct DidCloseNotebookDocumentParams {}

pub struct InlineCompletionParams {}

pub struct InlineCompletionList {}

pub struct InlineCompletionItem {}

pub struct InlineCompletionRegistrationOptions {}

pub struct TextDocumentContentParams {}

pub struct TextDocumentContentResult {}

pub struct TextDocumentContentRegistrationOptions {}

pub struct TextDocumentContentRefreshParams {}

pub struct RegistrationParams {}

pub struct UnregistrationParams {}

pub struct InitializeParams {}

pub struct InitializeResult {}

pub struct InitializeError {}

pub struct InitializedParams {}

pub struct DidChangeConfigurationParams {}

pub struct DidChangeConfigurationRegistrationOptions {}

pub struct ShowMessageParams {}

pub struct ShowMessageRequestParams {}

pub struct MessageActionItem {}

pub struct LogMessageParams {}

pub struct DidOpenTextDocumentParams {}

pub struct DidChangeTextDocumentParams {}

pub struct TextDocumentChangeRegistrationOptions {}

pub struct DidCloseTextDocumentParams {}

pub struct DidSaveTextDocumentParams {}

pub struct TextDocumentSaveRegistrationOptions {}

pub struct WillSaveTextDocumentParams {}

pub struct TextEdit {}

pub struct DidChangeWatchedFilesParams {}

pub struct DidChangeWatchedFilesRegistrationOptions {}

pub struct PublishDiagnosticsParams {}

pub struct CompletionParams {}

pub struct CompletionItem {}

pub struct CompletionList {}

pub struct CompletionRegistrationOptions {}

pub struct HoverParams {}

pub struct Hover {}

pub struct HoverRegistrationOptions {}

pub struct SignatureHelpParams {}

pub struct SignatureHelp {}

pub struct SignatureHelpRegistrationOptions {}

pub struct DefinitionParams {}

pub struct DefinitionRegistrationOptions {}

pub struct ReferenceParams {}

pub struct ReferenceRegistrationOptions {}

pub struct DocumentHighlightParams {}

pub struct DocumentHighlight {}

pub struct DocumentHighlightRegistrationOptions {}

pub struct DocumentSymbolParams {}

pub struct SymbolInformation {}

pub struct DocumentSymbol {}

pub struct DocumentSymbolRegistrationOptions {}

pub struct CodeActionParams {}

pub struct Command {}

pub struct CodeAction {}

pub struct CodeActionRegistrationOptions {}

pub struct WorkspaceSymbolParams {}

pub struct WorkspaceSymbol {}

pub struct WorkspaceSymbolRegistrationOptions {}

pub struct CodeLensParams {}

pub struct CodeLens {}

pub struct CodeLensRegistrationOptions {}

pub struct DocumentLinkParams {}

pub struct DocumentLink {}

pub struct DocumentLinkRegistrationOptions {}

pub struct DocumentFormattingParams {}

pub struct DocumentFormattingRegistrationOptions {}

pub struct DocumentRangeFormattingParams {}

pub struct DocumentRangeFormattingRegistrationOptions {}

pub struct DocumentRangesFormattingParams {}

pub struct DocumentOnTypeFormattingParams {}

pub struct DocumentOnTypeFormattingRegistrationOptions {}

pub struct RenameParams {}

pub struct RenameRegistrationOptions {}

pub struct PrepareRenameParams {}

pub struct ExecuteCommandParams {}

pub struct ExecuteCommandRegistrationOptions {}

pub struct ApplyWorkspaceEditParams {}

pub struct ApplyWorkspaceEditResult {}

pub struct WorkDoneProgressBegin {}

pub struct WorkDoneProgressReport {}

pub struct WorkDoneProgressEnd {}

pub struct SetTraceParams {}

pub struct LogTraceParams {}

pub struct CancelParams {}

pub struct ProgressParams {}

pub struct TextDocumentPositionParams {}

pub struct WorkDoneProgressParams {}

pub struct PartialResultParams {}

pub struct LocationLink {}

pub struct Range {}

pub struct ImplementationOptions {}

pub struct StaticRegistrationOptions {}

pub struct TypeDefinitionOptions {}

pub struct WorkspaceFoldersChangeEvent {}

pub struct ConfigurationItem {}

pub struct TextDocumentIdentifier {}

pub struct Color {}

pub struct DocumentColorOptions {}

pub struct FoldingRangeOptions {}

pub struct DeclarationOptions {}

pub struct Position {}

pub struct SelectionRangeOptions {}

pub struct CallHierarchyOptions {}

pub struct SemanticTokensOptions {}

pub struct SemanticTokensEdit {}

pub struct LinkedEditingRangeOptions {}

pub struct FileCreate {}

pub struct TextDocumentEdit {}

pub struct CreateFile {}

pub struct RenameFile {}

pub struct DeleteFile {}

pub struct ChangeAnnotation {}

pub struct FileOperationFilter {}

pub struct FileRename {}

pub struct FileDelete {}

pub struct MonikerOptions {}

pub struct TypeHierarchyOptions {}

pub struct InlineValueContext {}

pub struct InlineValueText {}

pub struct InlineValueVariableLookup {}

pub struct InlineValueEvaluatableExpression {}

pub struct InlineValueOptions {}

pub struct InlayHintLabelPart {}

pub struct MarkupContent {}

pub struct InlayHintOptions {}

pub struct RelatedFullDocumentDiagnosticReport {}

pub struct RelatedUnchangedDocumentDiagnosticReport {}

pub struct FullDocumentDiagnosticReport {}

pub struct UnchangedDocumentDiagnosticReport {}

pub struct DiagnosticOptions {}

pub struct PreviousResultId {}

pub struct NotebookDocument {}

pub struct TextDocumentItem {}

pub struct NotebookDocumentSyncOptions {}

pub struct VersionedNotebookDocumentIdentifier {}

pub struct NotebookDocumentChangeEvent {}

pub struct NotebookDocumentIdentifier {}

pub struct InlineCompletionContext {}

pub struct StringValue {}

pub struct InlineCompletionOptions {}

pub struct TextDocumentContentOptions {}

pub struct Registration {}

pub struct Unregistration {}

pub struct _InitializeParams {}

pub struct WorkspaceFoldersInitializeParams {}

pub struct ServerCapabilities {}

pub struct ServerInfo {}

pub struct VersionedTextDocumentIdentifier {}

pub struct SaveOptions {}

pub struct FileEvent {}

pub struct FileSystemWatcher {}

pub struct Diagnostic {}

pub struct CompletionContext {}

pub struct CompletionItemLabelDetails {}

pub struct InsertReplaceEdit {}

pub struct CompletionItemDefaults {}

pub struct CompletionItemApplyKinds {}

pub struct CompletionOptions {}

pub struct HoverOptions {}

pub struct SignatureHelpContext {}

pub struct SignatureInformation {}

pub struct SignatureHelpOptions {}

pub struct DefinitionOptions {}

pub struct ReferenceContext {}

pub struct ReferenceOptions {}

pub struct DocumentHighlightOptions {}

pub struct BaseSymbolInformation {}

pub struct DocumentSymbolOptions {}

pub struct CodeActionContext {}

pub struct CodeActionDisabled {}

pub struct CodeActionOptions {}

pub struct LocationUriOnly {}

pub struct WorkspaceSymbolOptions {}

pub struct CodeLensOptions {}

pub struct DocumentLinkOptions {}

pub struct FormattingOptions {}

pub struct DocumentFormattingOptions {}

pub struct DocumentRangeFormattingOptions {}

pub struct DocumentOnTypeFormattingOptions {}

pub struct RenameOptions {}

pub struct PrepareRenamePlaceholder {}

pub struct PrepareRenameDefaultBehavior {}

pub struct ExecuteCommandOptions {}

pub struct WorkspaceEditMetadata {}

pub struct SemanticTokensLegend {}

pub struct SemanticTokensFullDelta {}

pub struct OptionalVersionedTextDocumentIdentifier {}

pub struct AnnotatedTextEdit {}

pub struct SnippetTextEdit {}

pub struct ResourceOperation {}

pub struct CreateFileOptions {}

pub struct RenameFileOptions {}

pub struct DeleteFileOptions {}

pub struct FileOperationPattern {}

pub struct WorkspaceFullDocumentDiagnosticReport {}

pub struct WorkspaceUnchangedDocumentDiagnosticReport {}

pub struct NotebookCell {}

pub struct NotebookDocumentFilterWithNotebook {}

pub struct NotebookDocumentFilterWithCells {}

pub struct NotebookDocumentCellChanges {}

pub struct SelectedCompletionInfo {}

pub struct ClientInfo {}

pub struct ClientCapabilities {}

pub struct TextDocumentSyncOptions {}

pub struct WorkspaceOptions {}

pub struct TextDocumentContentChangePartial {}

pub struct TextDocumentContentChangeWholeDocument {}

pub struct CodeDescription {}

pub struct DiagnosticRelatedInformation {}

pub struct EditRangeWithInsertReplace {}

pub struct ServerCompletionItemOptions {}

pub struct MarkedStringWithLanguage {}

pub struct ParameterInformation {}

pub struct CodeActionKindDocumentation {}

pub struct NotebookCellTextDocumentFilter {}

pub struct FileOperationPatternOptions {}

pub struct ExecutionSummary {}

pub struct NotebookCellLanguage {}

pub struct NotebookDocumentCellChangeStructure {}

pub struct NotebookDocumentCellContentChanges {}

pub struct WorkspaceClientCapabilities {}

pub struct TextDocumentClientCapabilities {}

pub struct NotebookDocumentClientCapabilities {}

pub struct WindowClientCapabilities {}

pub struct GeneralClientCapabilities {}

pub struct WorkspaceFoldersServerCapabilities {}

pub struct FileOperationOptions {}

pub struct RelativePattern {}

pub struct TextDocumentFilterLanguage {}

pub struct TextDocumentFilterScheme {}

pub struct TextDocumentFilterPattern {}

pub struct NotebookDocumentFilterNotebookType {}

pub struct NotebookDocumentFilterScheme {}

pub struct NotebookDocumentFilterPattern {}

pub struct NotebookCellArrayChange {}

pub struct WorkspaceEditClientCapabilities {}

pub struct DidChangeConfigurationClientCapabilities {}

pub struct DidChangeWatchedFilesClientCapabilities {}

pub struct WorkspaceSymbolClientCapabilities {}

pub struct ExecuteCommandClientCapabilities {}

pub struct SemanticTokensWorkspaceClientCapabilities {}

pub struct CodeLensWorkspaceClientCapabilities {}

pub struct FileOperationClientCapabilities {}

pub struct InlineValueWorkspaceClientCapabilities {}

pub struct InlayHintWorkspaceClientCapabilities {}

pub struct DiagnosticWorkspaceClientCapabilities {}

pub struct FoldingRangeWorkspaceClientCapabilities {}

pub struct TextDocumentContentClientCapabilities {}

pub struct TextDocumentSyncClientCapabilities {}

pub struct TextDocumentFilterClientCapabilities {}

pub struct CompletionClientCapabilities {}

pub struct HoverClientCapabilities {}

pub struct SignatureHelpClientCapabilities {}

pub struct DeclarationClientCapabilities {}

pub struct DefinitionClientCapabilities {}

pub struct TypeDefinitionClientCapabilities {}

pub struct ImplementationClientCapabilities {}

pub struct ReferenceClientCapabilities {}

pub struct DocumentHighlightClientCapabilities {}

pub struct DocumentSymbolClientCapabilities {}

pub struct CodeActionClientCapabilities {}

pub struct CodeLensClientCapabilities {}

pub struct DocumentLinkClientCapabilities {}

pub struct DocumentColorClientCapabilities {}

pub struct DocumentFormattingClientCapabilities {}

pub struct DocumentRangeFormattingClientCapabilities {}

pub struct DocumentOnTypeFormattingClientCapabilities {}

pub struct RenameClientCapabilities {}

pub struct FoldingRangeClientCapabilities {}

pub struct SelectionRangeClientCapabilities {}

pub struct PublishDiagnosticsClientCapabilities {}

pub struct CallHierarchyClientCapabilities {}

pub struct SemanticTokensClientCapabilities {}

pub struct LinkedEditingRangeClientCapabilities {}

pub struct MonikerClientCapabilities {}

pub struct TypeHierarchyClientCapabilities {}

pub struct InlineValueClientCapabilities {}

pub struct InlayHintClientCapabilities {}

pub struct DiagnosticClientCapabilities {}

pub struct InlineCompletionClientCapabilities {}

pub struct NotebookDocumentSyncClientCapabilities {}

pub struct ShowMessageRequestClientCapabilities {}

pub struct ShowDocumentClientCapabilities {}

pub struct StaleRequestSupportOptions {}

pub struct RegularExpressionsClientCapabilities {}

pub struct MarkdownClientCapabilities {}

pub struct ChangeAnnotationsSupportOptions {}

pub struct ClientSymbolKindOptions {}

pub struct ClientSymbolTagOptions {}

pub struct ClientSymbolResolveOptions {}

pub struct ClientCompletionItemOptions {}

pub struct ClientCompletionItemOptionsKind {}

pub struct CompletionListCapabilities {}

pub struct ClientSignatureInformationOptions {}

pub struct ClientCodeActionLiteralOptions {}

pub struct ClientCodeActionResolveOptions {}

pub struct CodeActionTagOptions {}

pub struct ClientCodeLensResolveOptions {}

pub struct ClientFoldingRangeKindOptions {}

pub struct ClientFoldingRangeOptions {}

pub struct DiagnosticsCapabilities {}

pub struct ClientSemanticTokensRequestOptions {}

pub struct ClientInlayHintResolveOptions {}

pub struct ClientShowMessageActionItemOptions {}

pub struct CompletionItemTagOptions {}

pub struct ClientCompletionItemResolveOptions {}

pub struct ClientCompletionItemInsertTextModeOptions {}

pub struct ClientSignatureParameterInformationOptions {}

pub struct ClientCodeActionKindOptions {}

pub struct ClientDiagnosticsTagOptions {}

pub struct ClientSemanticTokensRequestFullDelta {}
