//! This module is automatically @generated by an xtask. Do not edit.
#![allow(
    deprecated,
    clippy::doc_lazy_continuation,
    unreachable_patterns,
    clippy::large_enum_variant,
    clippy::too_many_arguments,
    clippy::too_long_first_doc_paragraph,
    clippy::doc_markdown,
    clippy::match_same_arms,
    clippy::doc_link_with_quotes,
    clippy::manual_string_new,
    clippy::use_self,
    clippy::ref_option,
    rustdoc::invalid_codeblock_attributes
)]
#![cfg_attr(any(), rustfmt::skip)]

mod common;
mod enum_ors;
mod enumerations;
mod notifications;
mod requests;
mod structures;
mod type_aliases;

pub use common::*;
pub use enum_ors::*;
pub use enumerations::*;
pub use notifications::*;
pub use requests::*;
pub use structures::*;
pub use type_aliases::*;
