use std::fs;

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

const METAMODEL_URL: &str = "https://raw.githubusercontent.com/microsoft/language-server-protocol/gh-pages/_specifications/lsp/3.18/metaModel/metaModel.json";

mod schema {
    // TODO: Add CI check to ensure that the locally copied schema still matches the GitHub source.
    typify::import_types!("metaModel.schema.json");
}

fn main() {
    // Run the generator. This will eventually be moved to an xtask.
    let mut response = ureq::get(METAMODEL_URL).call().unwrap();

    let body = response.body_mut().read_to_string().unwrap();

    let model: schema::MetaModel = serde_json::from_str(&body).unwrap();

    println!(
        "Generating types for LSP version {} 🌟",
        model.meta_data.version
    );

    let preamble = quote! {
        //! This file is generated by an xtask. Do not edit.
    };

    let structures: Vec<TokenStream> = model
        .structures
        .into_iter()
        .map(|structure| {
            let name = format_ident!("{}", structure.name);

            quote! {
                pub struct #name {}
            }
        })
        .collect();

    let all_items = [&[preamble], &structures[..]].concat();

    let formatted_items: Vec<_> = all_items
        .into_iter()
        .map(|request| {
            let syntax_tree = syn::parse2(request).unwrap();

            prettyplease::unparse(&syntax_tree)
        })
        .collect();

    fs::write("src/generated.rs", formatted_items.join("\n")).unwrap();
}
